# 
# File. monitor_client.ini
# Date. 12/13/2020
# Description.
#        Set JAVA_HOME for monitor_client
# JAVA_HOME=/Users/amahasintunan/current-jdk
# JAVA_HOME=/home/amahasintunan/current-jdk
JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
# JAVA_HOME=C:\Program Files\Java\jdk-21.0.2
